services:
  - type: web
    name: allmyfriends-accounting
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        priority: 0
envVars:
  - key: NODE_VERSION
    value: 18.17.0
  - key: VITE_SUPABASE_URL
    sync: false  # This tells Render to get the value from the dashboard
  - key: VITE_SUPABASE_ANON_KEY
    sync: false  # This tells Render to get the value from the dashboard